# Generated by Django 5.2.14 on 2026-05-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sap_fuel", "SAP Fuel / Procurement"),
                            ("utility_electricity", "Utility Electricity"),
                            ("corporate_travel", "Corporate Travel"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "ingestion_method",
                    models.CharField(
                        choices=[
                            ("csv_upload", "CSV Upload"),
                            ("api_mock", "Mocked API"),
                        ],
                        max_length=16,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=512)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("processing_summary", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        help_text="Original row fields exactly as parsed from CSV/API."
                    ),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(
                        help_text="1-based line number in source file or batch index."
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of human-readable validation error strings.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["data_source", "row_number"],
            },
        ),
    ]
