# Generated by Django 5.2.14 on 2026-05-27 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingestion", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_sources",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_data_sources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rawrecord",
            name="data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_records",
                to="ingestion.datasource",
            ),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["tenant", "-uploaded_at"], name="ingestion_d_tenant__5f38ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["tenant", "processing_status"],
                name="ingestion_d_tenant__fc19c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawrecord",
            index=models.Index(
                fields=["data_source", "row_number"],
                name="ingestion_r_data_so_695d29_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rawrecord",
            constraint=models.UniqueConstraint(
                fields=("data_source", "row_number"),
                name="unique_raw_record_per_source_row",
            ),
        ),
    ]
