# Generated by Django 5.2.14 on 2026-05-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NormalizedEmissionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emission_scope",
                    models.CharField(
                        choices=[
                            ("scope1", "Scope 1"),
                            ("scope2", "Scope 2"),
                            ("scope3", "Scope 3"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="e.g. stationary_combustion, purchased_electricity, business_travel_air",
                        max_length=128,
                    ),
                ),
                (
                    "activity_date",
                    models.DateField(
                        help_text="Date activity occurred or billing period representative date."
                    ),
                ),
                (
                    "normalized_unit",
                    models.CharField(
                        help_text="Standard unit after conversion, e.g. liter, kwh, km.",
                        max_length=32,
                    ),
                ),
                (
                    "normalized_quantity",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "emission_factor",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="kg CO2e per normalized unit used at calculation time.",
                        max_digits=12,
                    ),
                ),
                (
                    "calculated_emissions_kg_co2e",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "source_system",
                    models.CharField(
                        help_text="Originating system label, e.g. sap_mm, utility_portal, concur_mock.",
                        max_length=64,
                    ),
                ),
                (
                    "suspicious_flag",
                    models.BooleanField(
                        default=False,
                        help_text="Set by rules e.g. utility usage spike > 2x rolling average.",
                    ),
                ),
                ("suspicious_reason", models.CharField(blank=True, max_length=512)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "locked_for_audit",
                    models.BooleanField(
                        default=False,
                        help_text="When True, record cannot be edited — audit-published state.",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlantCodeLookup",
            fields=[
                (
                    "code",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("plant_name", models.CharField(max_length=255)),
                (
                    "country",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 country code", max_length=2
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant code lookup",
                "verbose_name_plural": "Plant code lookups",
                "ordering": ["code"],
            },
        ),
    ]
