# Generated by Django 5.2.14 on 2026-05-27 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emissions", "0001_initial"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="normalizedemissionrecord",
            name="raw_record",
            field=models.OneToOneField(
                blank=True,
                help_text="Source row; null only for edge cases / manual entry later.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="normalized_record",
                to="ingestion.rawrecord",
            ),
        ),
    ]
