# Generated by Django 5.2.14 on 2026-05-27 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emissions", "0002_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="normalizedemissionrecord",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_emission_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="normalizedemissionrecord",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emission_records",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedemissionrecord",
            index=models.Index(
                fields=["tenant", "approval_status", "suspicious_flag"],
                name="emissions_n_tenant__6112d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedemissionrecord",
            index=models.Index(
                fields=["tenant", "emission_scope"],
                name="emissions_n_tenant__8c23e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedemissionrecord",
            index=models.Index(
                fields=["tenant", "-activity_date"],
                name="emissions_n_tenant__dc0dac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedemissionrecord",
            index=models.Index(
                fields=["tenant", "locked_for_audit"],
                name="emissions_n_tenant__59b5a1_idx",
            ),
        ),
    ]
