# Generated by Django 5.2.14 on 2026-05-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("data_source", "Data Source"),
                            ("raw_record", "Raw Record"),
                            (
                                "normalized_emission_record",
                                "Normalized Emission Record",
                            ),
                            ("tenant", "Tenant"),
                        ],
                        max_length=64,
                    ),
                ),
                ("entity_id", models.CharField(max_length=64)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("upload_started", "Upload Started"),
                            ("upload_completed", "Upload Completed"),
                            ("upload_failed", "Upload Failed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("locked", "Locked for Audit"),
                        ],
                        max_length=32,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
    ]
